=== patrickneubauer/XMLIntellEdit/source/at.ac.tuwien.big.xmltext/library3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- definition of simple types -->
  <xs:simpleType name="nameType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="32"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="sinceType">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
  <xs:simpleType name="isbnType">
     <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}-[0-9]{3}-[0-9]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="dimension">
     <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]|([1-9][0-9]+))([.][0-9]+)? x ([0-9]|([1-9][0-9]+))([.][0-9]+)? x ([0-9]|([1-9][0-9]+))([.][0-9]+)? (centimeters|cm|in|inches)"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- definition of complex types -->
  <xs:complexType name="libraryType">
  	<xs:sequence>
  		<xs:element maxOccurs="unbounded" minOccurs="0" name="book" type="bookType"/>
  		<xs:element maxOccurs="unbounded" minOccurs="0" name="customer" type="customerType"/>
  	</xs:sequence>
  </xs:complexType>
  <xs:complexType name="bookType">
    <xs:sequence>
      <xs:element name="name" type="xs:ID"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="author" type="nameType"/>
      <xs:element name="pages" type="xs:int"/>
      <xs:element name="dimension" type="dimension"/>
      <xs:element minOccurs="0" name="download" type="xs:anyURI"/>
      <xs:element minOccurs="0" name="bookInfo" type="bookInfoType"/>
    </xs:sequence>
    <xs:attribute name="isbn" type="isbnType" use="required"/>
  </xs:complexType>
  <xs:complexType name="customerType">
  	<xs:sequence>
  		<xs:element name="firstName" type="xs:string"/>
  		<xs:element name="lastName" type="xs:string"/>
  		<xs:element minOccurs="0" name="borrowedBookId" type="xs:IDREF"/>
  		<xs:element minOccurs="0" name="borrowedBookSince" type="sinceType"/>
  	</xs:sequence>
  </xs:complexType>
  <xs:complexType name="bookInfoType">
  	<xs:sequence>
		<xs:any maxOccurs="unbounded" namespace="##any" processContents="lax"/>
  	</xs:sequence>
  </xs:complexType>     
   <!-- root element -->
  <xs:element name="library" type="libraryType"/>   
</xs:schema>

=== patrickneubauer/XMLIntellEdit/source/at.ac.tuwien.big.xmltext/examples/library3.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library3.xsd">
<book 
	isbn="001-23-4567-080-9">
	<name>BuchName</name>
    <title>Unbeschriebenes Blatt</title>
    <author>Anonym</author>
    <pages>15</pages>
    <dimension>5 x 2 x 2 cm</dimension>
</book>
<customer>
	<firstName>Max</firstName>
	<lastName>Mustermann</lastName>
	<borrowedBookId>BuchName</borrowedBookId>
</customer> 

</library>

=== patrickneubauer/XMLIntellEdit/source/at.ac.tuwien.big.xmltext/examples/library4.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library3.xsd">
<book 
	isbn="0123456789">
	<name>BuchName</name>
    <title>Unbeschriebenes Blatt</title>
    <author>Anonym</author>
    <dimension>5 x 2 x 2 cm</dimension>
</book>
<customer>
	<firstName>Max</firstName>
	<lastName>Mustermann</lastName>
	<borrowedBookId>BuchName</borrowedBookId>
</customer> 

</library>
